apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-kubernetes
spec:
  selector:
    matchLabels:
      app: springboot-kubernetes
  template:
    metadata:
      labels:
        app: springboot-kubernetes
    spec:
      containers:
        - image: fsantaniello/springboot-kubernetes:{{tag}}
          imagePullPolicy: IfNotPresent
          name: springboot-kubernetes
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-kubernetes
spec:
  selector:
    app: springboot-kubernetes
  ports:
    - nodePort: 32024
      port: 8080
      protocol: TCP
      targetPort: 8080
  type: NodePort