apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-kubernetes
spec:
  selector:
    matchLabels:
      app: springboot-kubernetes
      name: springboot-kubernetes
  template:
    metadata:
      labels:
        app: springboot-kubernetes
    spec:
      containers:
        - name: springboot-kubernetes
          image: fsantaniello/springboot-kubernetes:{{tag}}
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          resources: {}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: springboot-kubernetes
  name: springboot-kubernetes
spec:
#  clusterIP: 10.96.12.208
#  clusterIPs:
#    - 10.96.12.208
#  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 32024
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: springboot-kubernetes
  sessionAffinity: None
  type: NodePort