apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-kubernetes
spec:
  selector:
    matchLabels:
      app: springboot-kubernetes
      name: springboot-kubernetes
  template:
    metadata:
      labels:
        app: springboot-kubernetes
    spec:
      containers:
        - name: springboot-kubernetes
          image: fsantaniello/springboot-kubernetes:{{tag}}
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          resources: {}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: springboot-kubernetes
  name: springboot-kubernetes
spec:
  selector:
    app: springboot-kubernetes
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer